app:
  image: ghcr.io/xorbaytech/xorbay-notification-system:${IMAGE_TAG}
  ports:
    - "3002:3000"
  environment:
    NODE_ENV: production
    DATABASE_URL: ${DATABASE_URL}
    REDIS_HOST: ${REDIS_HOST}
    REDIS_PORT: ${REDIS_PORT}
    PUBLISHER_API_KEY: ${PUBLISHER_API_KEY}
  extra_hosts:
    - "host.docker.internal:host-gateway"